spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/roundleafcafe
    username: sa
    password:

#  sql:
#    init:
#      mode: always
  security:
    user:
      name: nhs0912
      password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  integration:
      management:
        default-logging-enabled: true

logging:
    level:
      org.hibernate.SQL: error
      org.hibernate.type: error
      org.springframework.boot.autoconfigure: error
      org.apache.coyote.http11: debug
